sudo: false
language: node_js
node_js:
- '10'
cache: yarn
services:
- docker
env:
  global:
  - NODE_ENV=CI
  - EVE_API_HOST=http://eve-api:4000/graphql
  - EVE_LOGIN_URL=https://login.eveonline.com
  - EVE_CLIENT_ID=6824e828c9f64b61abecdcb5c13496c5
  - EVE_CHARACTER_REDIRECT_URL=https://eve-app.geekspace.us/characters
stages:
- install
- test
- build
jobs:
  include:
  - stage: install
    script:
    - yarn install
  - stage: test
    script:
    - CI=true npm run coveralls
  - stage: build
    script:
    - yarn build
    - rm -rf node_modules
    - yarn install --production --ignore-scripts
    - docker build -t travis-ci-build-stage -f Dockerfile.ci .
    - docker tag travis-ci-build-stage gcr.io/$GC_PROJECT_ID/eve-app:$TRAVIS_BUILD_NUMBER
    - openssl aes-256-cbc -K $encrypted_51d2d66657cc_key -iv $encrypted_51d2d66657cc_iv -in gce.json.enc -out gce.json -d
    - cat gce.json | docker login -u _json_key --password-stdin https://gcr.io
    - docker push gcr.io/$GC_PROJECT_ID/eve-app:$TRAVIS_BUILD_NUMBER
    if: "(branch = dev OR branch = master) AND type = push"
