apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ include "eve-app.fullname" . }}-crt
spec:
  secretName: eve-app-crt
  dnsNames:
  {{- range .Values.ingress.hosts }}
  - {{ .host }}
  {{- end}}
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
        {{- range .Values.ingress.hosts }}
        - {{ .host }}
        {{- end }}
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
