apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eve-app.name" . }}-secret
  labels:
{{ include "eve-app.labels" . | indent 4 }}
type: Opaque
data:
  {{ if .Values.eveClientSecret }}
  eve-client-secret: {{ .Values.eveClientSecret | b64enc | quote }}
  {{ else }}
  eve-client-secret: {{ randAlphaNum 32 | b64enc | quote }}
  {{ end }}
  {{ if .Values.auth0ClientSecret }}
  auth0-client-secret: {{ .Values.auth0ClientSecret | b64enc | quote }}
  {{ else }}
  auth0-client-secret: {{ randAlphaNum 32 | b64enc | quote }}
  {{ end }}
  {{ if .Values.cookieSecret }}
  cookie-secret: {{ .Values.cookieSecret | b64enc | quote }}
  {{ else }}
  cookie-secret: {{ randAlphaNum 32 | b64enc | quote }}
  {{ end }}
