apiVersion: apps/v1
kind: Deployment
metadata:
  name: eve-warehouse-api-v1
spec:
  template:
    spec:
      containers:
        - name: eve-warehouse-app
          env:
            - name: LOG_LEVEL
              value: info
