---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eve-warehouse-app
  labels:
    account: eve-warehouse-app
imagePullSecrets:
  - name: gcr-json-key
---
apiVersion: v1
kind: Service
metadata:
  name: eve-warehouse-app
  labels:
    service: eve-warehouse-app
spec:
  ports:
    - port: 8080
      name: http
