apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: staging-
commonLabels:
  variant: staging

namespace: eve-warehouse-staging

bases:
  - ../../base

images:
  - name: eve-app-image
    newTag: 42fb3c3c771a53cc8bbde2b57f67435611fa37259d82e10f4c018bb62e3a78fc
    newName: gcr.io/personal-248114/eve-app@sha256

secretGenerator:
  - name: eve-warehouse-app-secret
    envs:
      - secrets.env

patchesStrategicMerge:
  - custom-env.yaml

resources:
  - namespace.yaml
  - gateway.yaml
  - destination-rule.yaml
  - virtual-service.yaml
